language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge ttfautohint
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontcrunch.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
before_script:
- mkdir -p builds/build
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-build.py .
  2>&1 | tee -a builds/build/buildlog.txt
branches:
  only:
  - master
after_script:
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-report.py builds/build
- rm -rf builds/build/sources
- rm -rf builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-travis-deploy.py
env:
  global:
    secure: nIM8nrS/pl6rZ384a9f5EmGfE6AQG3LRZdkLBLw+L5byY5vi26IQoklqSNFUiwtw5gXUKGaYVP01WmLhRwFo9ZQ7O1OBsbsp7wy66k27oub0q0RxfPhLE8A3w3q6nUlL++CkqQAzJAILHsZQeQh0YlfJ0Cx4mqoK7uF8Ab0xTXc=
